#!/bin/sh

set -e

private_key="${1:-${SSH_PRIVATE_KEY_BASE64}}"
known_hosts="${2:-${SSH_KNOWN_HOSTS}}"

agent_response="$(ssh-agent -s)"

eval "${agent_response}"

echo "${private_key}" | base64 -d | tr -d '\r' | ssh-add -

if [ -n "${known_hosts}" ]; then
  mkdir -p ~/.ssh
  echo "${known_hosts}" | tee -a ~/.ssh/known_hosts 1>&2
fi

echo "${agent_response}"
